services:
  db:
    image: mysql:8.3
    container_name: "mysql_test"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_test_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data_test:/var/lib/mysql
      - db_my.conf_test:/etc/mysql/conf.d/my.conf
      - db_sql_test:/docker-entrypoint-initdb.d

  php:
    build: ./docker/php
    container_name: "php-fpm"
    restart: unless-stopped
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx:latest
    container_name: "nginx_test"
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin_test"
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: secret
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/var/lib/phpmyadmin/sessions
  
  node:
    image: node:24-alpine
    container_name: "node24-alpine"
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www
    working_dir: /var/www

  # 作業用コンテナ
  workspace:
    image: php:8.2-cli
    container_name: "workspace"
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    command: tail -f /dev/null  # コンテナを永続化

  mail:
    image: mailhog/mailhog
    container_name: "mailhog"
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - 8025:8025

volumes:
  db_data_test:
  db_my.conf_test:
  db_sql_test:
